name: Refresh

on:
  workflow_dispatch:
  schedule:
    - cron: '05 14 * * *' # Runs every day at 14:05 UTC. 5 min added to ensure posts scheduled for on the hour go out.

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger GitHub pages rebuild
        env:
          USER_TOKEN: ${{ secrets.USER_TOKEN }}
        run: |
          curl --fail --request POST --url https://api.github.com/repos/${{ github.repository }}/pages/builds --header "Authorization: bearer $USER_TOKEN"